import { ArrowRight, Bell, Building2, CalendarDays, ClipboardCheck } from 'lucide-react'
import { useQueries, useQuery } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { api } from '../api'
import type { ResourceName } from '../types'
import { ErrorState, Loading } from '../components/ResourcePage'
const resources: ResourceName[] = ['schedules','rooms','events','announcements','assignments']
export function Overview(){const results=useQueries({queries:resources.map(resource=>({queryKey:[resource],queryFn:()=>api.list(resource)}))});const me=useQuery({queryKey:['me'],queryFn:api.me});if(results.some(x=>x.isLoading))return <main className="page"><Loading/></main>;if(results.some(x=>x.isError))return <main className="page"><ErrorState message="The campus API is unavailable." retry={()=>results.forEach(x=>x.refetch())}/></main>;const [schedules,rooms,events,announcements,assignments]=results.map(x=>x.data!);const pending=assignments.items.filter((x:any)=>x.status==='pending');const nextEvents=events.items.filter((x:any)=>x.status==='upcoming').slice(0,3);return <main className="page"><div className="hero"><div><span className="eyebrow">Friday, 4 September</span><h1>Good afternoon,<br/>{me.data?.name.split(' ')[0]??'Sakibul'}.</h1><p>Your campus, organized. Here’s what needs your attention.</p></div><div className="hero-orb"><span>{pending.length}</span><small>open tasks</small></div></div><div className="stats"><Stat icon={<CalendarDays/>} value={schedules.total} label="Weekly classes" color="green"/><Stat icon={<Building2/>} value={rooms.total} label="Campus rooms" color="blue"/><Stat icon={<ClipboardCheck/>} value={pending.length} label="Pending work" color="orange"/><Stat icon={<Bell/>} value={announcements.total} label="Announcements" color="purple"/></div><div className="overview-grid"><section className="card panel"><PanelTitle title="Campus events" to="/events"/>{nextEvents.map((event:any)=><div className="timeline-item" key={event.id}><div><strong>{new Date(`${event.date}T00:00:00`).getDate()}</strong><small>SEP</small></div><section><h3>{event.name}</h3><p>{event.start_time} · {event.venue}</p></section><span className="pill">{event.status}</span></div>)}</section><section className="card panel"><PanelTitle title="Assignments" to="/assignments"/>{pending.slice(0,4).map((item:any)=><div className="deadline" key={item.id}><span>{item.course}</span><div><h3>{item.title}</h3><p>Due {item.deadline} · {item.marks} marks</p></div></div>)}</section></div></main>}
function PanelTitle({title,to}:{title:string;to:string}){return <div className="panel-title"><div><span className="eyebrow">Coming up</span><h2>{title}</h2></div><Link to={to}>View all <ArrowRight size={15}/></Link></div>}
function Stat({icon,value,label,color}:{icon:React.ReactNode;value:number;label:string;color:string}){return <div className="card stat"><span className={color}>{icon}</span><div><strong>{value}</strong><small>{label}</small></div></div>}
